/**
 * utils/qrParser.ts
 * Structured parsing for QR codes scanned on the Scan-to-Donate screen.
 *
 * Recognised payloads, in match order:
 *   1. IndigoPay deep link      stellar-indigopay://donate?projectId=X&amount=Y&memo=Z
 *   2. Legacy deep link         indigopay://donate?wallet=G...&project=X&amount=Y
 *   3. SEP-0007 payment URI     web+stellar:pay?destination=G...&amount=Y&memo=Z
 *      (this is what the web app's WalletAddressQRCode component encodes)
 *   4. Raw Stellar address      G... (56 chars)
 *   5. URL containing a Stellar address anywhere in it
 *
 * Anything else parses as { type: "unknown" } so the scan screen can show
 * an explicit "not a valid IndigoPay QR" error instead of failing silently.
 */
import { isValidStellarAddress } from "./stellarValidation";

export interface ParsedQR {
  type: "donate_link" | "stellar_address" | "unknown";
  projectId?: string;
  address?: string;
  amount?: string;
  memo?: string;
  raw: string;
}

const DEEP_LINK_RE = /^stellar-indigopay:\/\/donate\?(.+)$/i;
const LEGACY_DEEP_LINK_RE = /^indigopay:\/\/donate\?(.+)$/i;
const SEP0007_RE = /^web\+stellar:pay\?(.+)$/i;
const RAW_ADDRESS_RE = /^(G[A-Z0-9]{55})$/;
const EMBEDDED_ADDRESS_RE = /(G[A-Z0-9]{55})/;

/** Keep only amounts that are positive finite numbers ("50", "12.5"). */
function sanitizeAmount(value: string | null): string | undefined {
  if (!value) return undefined;
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return undefined;
  return value.trim();
}

/** Stellar text memos max out at 28 bytes; trim anything longer. */
function sanitizeMemo(value: string | null): string | undefined {
  if (!value) return undefined;
  const trimmed = value.trim();
  return trimmed ? trimmed.slice(0, 28) : undefined;
}

export function parseQRData(data: string): ParsedQR {
  const raw = typeof data === "string" ? data : String(data ?? "");
  const input = raw.trim();

  // Pattern 1: IndigoPay deep link with an embedded projectId.
  const deepLinkMatch = input.match(DEEP_LINK_RE);
  if (deepLinkMatch) {
    const params = new URLSearchParams(deepLinkMatch[1]);
    const projectId = params.get("projectId")?.trim() || undefined;
    const address = params.get("address")?.trim();
    if (!projectId && !isValidStellarAddress(address)) {
      return { type: "unknown", raw };
    }
    return {
      type: "donate_link",
      projectId,
      address: isValidStellarAddress(address) ? address : undefined,
      amount: sanitizeAmount(params.get("amount")),
      memo: sanitizeMemo(params.get("memo")),
      raw,
    };
  }

  // Pattern 2: legacy deep link (pre-#84 QR codes already in the wild).
  const legacyMatch = input.match(LEGACY_DEEP_LINK_RE);
  if (legacyMatch) {
    const params = new URLSearchParams(legacyMatch[1]);
    const wallet = params.get("wallet")?.trim() ?? "";
    if (!isValidStellarAddress(wallet)) {
      return { type: "unknown", raw };
    }
    return {
      type: "donate_link",
      projectId: params.get("project")?.trim() || undefined,
      address: wallet,
      amount: sanitizeAmount(params.get("amount")),
      memo: sanitizeMemo(params.get("memo")),
      raw,
    };
  }

  // Pattern 3: SEP-0007 pay URI, as generated by WalletAddressQRCode on web.
  const sepMatch = input.match(SEP0007_RE);
  if (sepMatch) {
    const params = new URLSearchParams(sepMatch[1]);
    const destination = params.get("destination")?.trim() ?? "";
    if (!isValidStellarAddress(destination)) {
      return { type: "unknown", raw };
    }
    return {
      type: "stellar_address",
      address: destination,
      amount: sanitizeAmount(params.get("amount")),
      memo: sanitizeMemo(params.get("memo")),
      raw,
    };
  }

  // Pattern 4: bare Stellar public key.
  const addressMatch = input.match(RAW_ADDRESS_RE);
  if (addressMatch) {
    return { type: "stellar_address", address: addressMatch[1], raw };
  }

  // Pattern 5: any other URL / text with a Stellar address embedded in it.
  const embeddedMatch = input.match(EMBEDDED_ADDRESS_RE);
  if (embeddedMatch) {
    return { type: "stellar_address", address: embeddedMatch[1], raw };
  }

  return { type: "unknown", raw };
}
