apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stellar-indigopay

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - postgres-standby.yaml
  - postgres-exporter.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-backend-postgres.yaml
  - networkpolicy-allow-backend-redis.yaml
  - networkpolicy-allow-frontend-backend.yaml
  - networkpolicy-allow-ingress-backend.yaml
  - networkpolicy-allow-prometheus-scrape.yaml
  - networkpolicy-allow-backend-egress-external.yaml
  - networkpolicy-allow-postgres-replication.yaml
  - networkpolicy-allow-exporter-postgres.yaml
  - postgres-failover-script.yaml
  - postgres-failover-job.yaml
  - postgres-failover-rbac.yaml
